name: autoglosser
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  collection: ^1.17.1
  json_annotation: ^4.8.1
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.1
  msix: ^3.15.1

flutter:
  uses-material-design: false
  fonts:
  - family: NotoSansSC
    fonts:
      - asset: fonts/NotoSansSC-Thin.otf
        weight: 100
      - asset: fonts/NotoSansSC-Light.otf
        weight: 300
      - asset: fonts/NotoSansSC-Regular.otf
      - asset: fonts/NotoSansSC-Medium.otf
        weight: 500
      - asset: fonts/NotoSansSC-Bold.otf
        weight: 700
      - asset: fonts/NotoSansSC-Black.otf
        weight: 900

msix_config:
  display_name: autoglosser
  logo_path: web\icons\Icon-512.png
  install_certificate: false
